import type { Metadata, Viewport } from "next";
import "./globals.css";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Unsub Hero",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-mod-js" suppressHydrationWarning>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <link href="https://fonts.googleapis.com" rel="preconnect" />
        <link href="https://fonts.gstatic.com" rel="preconnect" crossOrigin="anonymous" />
        <link
          href="https://cdn.prod.website-files.com/6929c116366a14507fc8424d/css/aeline.webflow.shared.113d25edf.min.css"
          rel="stylesheet"
          type="text/css"
          crossOrigin="anonymous"
        />

        <style dangerouslySetInnerHTML={{ __html: `
          .button[data-wf--button--variant="base"],
          .button-arrow,
          .button-arrow_wrap,
          .button-arrow .button-arrow_bg,
          .button-arrow_bg {
            background-color: #000000 !important;
            color: #ffffff !important;
            border-color: #000000 !important;
          }
          .button[data-wf--button--variant="base"]:hover,
          .button-arrow:hover,
          .button-arrow:hover .button-arrow_bg {
            background-color: #1a1a1a !important;
            border-color: #1a1a1a !important;
          }
          .button-arrow_text .text_button {
            color: #ffffff !important;
          }
          .button[data-wf--button--variant="base"] div {
            color: #ffffff !important;
          }
        `}} />
      </head>
      <body className="bg-primary" suppressHydrationWarning>
        {children}
        <Script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" strategy="beforeInteractive" />
        <Script id="webfont-init" strategy="beforeInteractive">{`WebFont.load({ google: { families: ["Inter:300,400,500,600,700", "Plus Jakarta Sans:300,400,500,600,700"] } });`}</Script>
        
        {/* GSAP from head */}
        <Script src="https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist/gsap.min.js" strategy="beforeInteractive" />
        <Script src="https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist/ScrollTrigger.min.js" strategy="beforeInteractive" />
        <Script src="https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist/Draggable.min.js" strategy="beforeInteractive" />
        <Script src="https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist/InertiaPlugin.min.js" strategy="beforeInteractive" />
        <Script src="https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist/Observer.min.js" strategy="beforeInteractive" />
        <Script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js" strategy="beforeInteractive" />
        
        {/* Scripts from bottom of body */}
        <Script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=6929c116366a14507fc8424d" strategy="beforeInteractive" crossOrigin="anonymous" />
        <Script src="https://cdn.prod.website-files.com/6929c116366a14507fc8424d/js/webflow.schunk.36b8fb49256177c8.js" strategy="lazyOnload" crossOrigin="anonymous" />
        <Script src="https://cdn.prod.website-files.com/6929c116366a14507fc8424d/js/webflow.schunk.7fa942c6f9da5827.js" strategy="lazyOnload" crossOrigin="anonymous" />
        <Script src="https://cdn.prod.website-files.com/6929c116366a14507fc8424d/js/webflow.schunk.4ed80055bdae3496.js" strategy="lazyOnload" crossOrigin="anonymous" />
        <Script src="https://cdn.prod.website-files.com/6929c116366a14507fc8424d/js/webflow.ec325c54.28244e4c1d8bb63f.js" strategy="lazyOnload" crossOrigin="anonymous" />
        <Script src="https://cdn.prod.website-files.com/gsap/3.15.0/gsap.min.js" strategy="beforeInteractive" />
        <Script src="https://cdn.prod.website-files.com/gsap/3.15.0/ScrollTrigger.min.js" strategy="beforeInteractive" />
        <Script src="https://cdn.prod.website-files.com/gsap/3.15.0/SplitText.min.js" strategy="beforeInteractive" />
        <Script id="gsap-register-init" strategy="beforeInteractive">{`gsap.registerPlugin(ScrollTrigger,SplitText);`}</Script>
      </body>
    </html>
  );
}
